/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controlador.CtrlBeneficiarios;
import Modelo.Beneficiario;
import Modelo.ConsultasBeneficiario;
import java.text.SimpleDateFormat;
import java.util.Date;

/**
 *
 * @author victor
 */
public class frmAfiliado extends javax.swing.JInternalFrame {

    /**
     * Creates new form frmAfiliado2
     */
    public frmAfiliado() {
        initComponents();
        java.util.Date fecha = new Date();
        SimpleDateFormat formato = new SimpleDateFormat("yyyy-MM-dd");
        txtFechaAfiliacion.setText(formato.format(fecha));
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTPaneles = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txtPlantel = new javax.swing.JTextField();
        txtQnaAfiliacion = new javax.swing.JTextField();
        txtCategoria = new javax.swing.JTextField();
        txtRfc = new javax.swing.JTextField();
        txtNombre = new javax.swing.JTextField();
        txtEmpleado = new javax.swing.JTextField();
        txtSueldo = new javax.swing.JTextField();
        txtCorreo = new javax.swing.JTextField();
        txtDireccion = new javax.swing.JTextField();
        txtTelefono = new javax.swing.JTextField();
        txtCelular = new javax.swing.JTextField();
        btnEliminar = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();
        btnBuscar = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();
        btnBuscarNomina = new javax.swing.JButton();
        jLabel19 = new javax.swing.JLabel();
        cbSindicato = new javax.swing.JComboBox<>();
        jLabel20 = new javax.swing.JLabel();
        cbEstadoCivil = new javax.swing.JComboBox<>();
        jLabel21 = new javax.swing.JLabel();
        cbSexo = new javax.swing.JComboBox<>();
        jLabel22 = new javax.swing.JLabel();
        fechaIngreso = new com.toedter.calendar.JDateChooser();
        btnAlta = new javax.swing.JButton();
        txtFechaAfiliacion = new javax.swing.JTextField();
        jPSegundoTermino = new javax.swing.JPanel();
        btnAltaBeneficiarioSegundoTermino = new javax.swing.JButton();
        btnEliminaBeneficiarioSegundoTermino = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTBeneficiariosSegundoTermino = new javax.swing.JTable();
        jLabel23 = new javax.swing.JLabel();
        txtNombreSegundoTermino = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        cbParenSegundoTermino = new javax.swing.JComboBox<>();
        jLabel26 = new javax.swing.JLabel();
        fechaSegundoTermino = new com.toedter.calendar.JDateChooser();
        BtnModificarSegundoTermino = new javax.swing.JButton();
        jPTestamentaria = new javax.swing.JPanel();
        txtNombre1 = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        txtPor1 = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        cbParen1 = new javax.swing.JComboBox<>();
        jLabel18 = new javax.swing.JLabel();
        fecha1 = new com.toedter.calendar.JDateChooser();
        btnAltaBeneficiario = new javax.swing.JButton();
        btnEliminaBeneficiario = new javax.swing.JButton();
        btnModificaBenficiario = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTBeneficiarios = new javax.swing.JTable();
        jLabel15 = new javax.swing.JLabel();
        btnModificarBeneficiario = new javax.swing.JButton();
        jPTestamentaria1 = new javax.swing.JPanel();
        txtNombreBaja = new javax.swing.JTextField();
        btnBajaJubilado = new javax.swing.JButton();
        btnAltaPrograma = new javax.swing.JButton();
        jLabel29 = new javax.swing.JLabel();
        btnModificarBajaPrograma = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        txtfechabajaprograma = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        txtQnaBajaPrograma = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        txtNumeroEmpleadoBaja = new javax.swing.JTextField();
        btnBuscarJubilado = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setTitle("Afiliado");

        jLabel1.setText("Fecha ");

        jLabel2.setText("Qna Afiliacion");

        jLabel4.setText("Rfc");

        jLabel5.setText("Nombre");

        jLabel6.setText("Direccion");

        jLabel7.setText("Plantel");

        jLabel8.setText("Categoria");

        jLabel9.setText("Telefono");

        jLabel10.setText("Celular");

        jLabel11.setText("# Empleado");

        jLabel12.setText("Correo");

        jLabel13.setText("Sueldo");

        txtEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmpleadoActionPerformed(evt);
            }
        });

        btnEliminar.setText("Eliminar");

        btnModificar.setText("Modificar");

        btnBuscar.setText("Buscar");

        btnLimpiar.setText("Limpiar");

        btnBuscarNomina.setText("Buscar Nomina");

        jLabel19.setText("Sindicato");

        cbSindicato.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "CONFIANZA", "SECCION LXIII", "SITCOBACH", "SUTCOBACH", "SECCION COBACH" }));

        jLabel20.setText("Estado Civil");

        cbEstadoCivil.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Soltero(a)", "Casado(a)", "Union Libre", "Divorciado(a)", "Viudo(a)" }));

        jLabel21.setText("Sexo");

        cbSexo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Masculino", "Femenino" }));

        jLabel22.setText("Fecha Ingreso");

        fechaIngreso.setDateFormatString("yyyy/MM/dd");

        btnAlta.setText("Alta");

        txtFechaAfiliacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFechaAfiliacionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnAlta)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnEliminar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnModificar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnBuscar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnLimpiar)
                        .addGap(18, 18, 18)
                        .addComponent(btnBuscarNomina))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtFechaAfiliacion, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addGap(217, 217, 217)
                            .addComponent(jLabel2)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txtQnaAfiliacion, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jLabel7)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txtPlantel, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(10, 10, 10)
                            .addComponent(jLabel8)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txtCategoria))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel4)
                            .addGap(18, 18, 18)
                            .addComponent(txtRfc, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(jLabel5)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(txtNombre))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel6)
                            .addGap(18, 18, 18)
                            .addComponent(txtDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jLabel9)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txtTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel19)
                            .addGap(18, 18, 18)
                            .addComponent(cbSindicato, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel11)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txtEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(jLabel13)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txtSueldo, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txtCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jLabel10)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txtCelular, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel20)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cbEstadoCivil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbSexo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel22)
                        .addGap(18, 18, 18)
                        .addComponent(fechaIngreso, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(145, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8)
                    .addComponent(txtQnaAfiliacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPlantel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtFechaAfiliacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtRfc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jLabel12)
                    .addComponent(txtEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSueldo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13)
                    .addComponent(jLabel10)
                    .addComponent(txtCelular, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel9)
                    .addComponent(txtDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel19)
                    .addComponent(cbSindicato, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel20)
                        .addComponent(cbEstadoCivil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel21)
                        .addComponent(jLabel22)
                        .addComponent(cbSexo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(fechaIngreso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEliminar)
                    .addComponent(btnModificar)
                    .addComponent(btnBuscar)
                    .addComponent(btnLimpiar)
                    .addComponent(btnBuscarNomina)
                    .addComponent(btnAlta))
                .addContainerGap(70, Short.MAX_VALUE))
        );

        jTPaneles.addTab("Afiliado", jPanel1);

        btnAltaBeneficiarioSegundoTermino.setText("Alta Beneficiario Segundo Termino");

        btnEliminaBeneficiarioSegundoTermino.setText("Eliminar Beneficiario Segundo Termino");

        jTBeneficiariosSegundoTermino.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre", "Parentesco", "Fecha", "Id", "Numero"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                true, true, true, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTBeneficiariosSegundoTermino.setColumnSelectionAllowed(true);
        jScrollPane2.setViewportView(jTBeneficiariosSegundoTermino);
        jTBeneficiariosSegundoTermino.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);

        jLabel23.setText("Nombre");

        txtNombreSegundoTermino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreSegundoTerminoActionPerformed(evt);
            }
        });

        jLabel25.setText("Parentesco");

        cbParenSegundoTermino.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Hijo(a)", "Esposo(a)", "Concubino(a)", "Madre", "Padre", "Amigo(a)", "Novio(a)", "Conocido(a)", " ", " " }));
        cbParenSegundoTermino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbParenSegundoTerminoActionPerformed(evt);
            }
        });

        jLabel26.setText("Fecha Nac.");

        fechaSegundoTermino.setDateFormatString("yyyy/MM/dd");

        BtnModificarSegundoTermino.setText("Modificar Beneficiario Segundo Termino");

        javax.swing.GroupLayout jPSegundoTerminoLayout = new javax.swing.GroupLayout(jPSegundoTermino);
        jPSegundoTermino.setLayout(jPSegundoTerminoLayout);
        jPSegundoTerminoLayout.setHorizontalGroup(
            jPSegundoTerminoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPSegundoTerminoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPSegundoTerminoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPSegundoTerminoLayout.createSequentialGroup()
                        .addComponent(jLabel23)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNombreSegundoTermino, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel25)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbParenSegundoTermino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel26)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(fechaSegundoTermino, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPSegundoTerminoLayout.createSequentialGroup()
                        .addComponent(btnAltaBeneficiarioSegundoTermino)
                        .addGap(18, 18, 18)
                        .addComponent(btnEliminaBeneficiarioSegundoTermino)
                        .addGap(18, 18, 18)
                        .addComponent(BtnModificarSegundoTermino, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 674, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(122, Short.MAX_VALUE))
        );
        jPSegundoTerminoLayout.setVerticalGroup(
            jPSegundoTerminoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPSegundoTerminoLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPSegundoTerminoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPSegundoTerminoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel23)
                        .addComponent(txtNombreSegundoTermino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel25)
                        .addComponent(cbParenSegundoTermino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel26))
                    .addComponent(fechaSegundoTermino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPSegundoTerminoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAltaBeneficiarioSegundoTermino)
                    .addComponent(btnEliminaBeneficiarioSegundoTermino)
                    .addComponent(BtnModificarSegundoTermino))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(59, Short.MAX_VALUE))
        );

        jTPaneles.addTab("Segundo Termino", jPSegundoTermino);

        txtNombre1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombre1ActionPerformed(evt);
            }
        });

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel16.setText("%");

        txtPor1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPor1ActionPerformed(evt);
            }
        });

        jLabel17.setText("Parentesco");

        cbParen1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Hijo(a)", "Esposo(a)", "Concubino(a)", "Madre", "Padre", "Amigo(a)", "Novio(a)", "Conocido(a)", " " }));

        jLabel18.setText("Fecha Nac.");

        fecha1.setDateFormatString("yyyy/MM/dd");

        btnAltaBeneficiario.setText("Alta Beneficiario");

        btnEliminaBeneficiario.setText("Eliminar Beneficiario");

        btnModificaBenficiario.setText("Modificar Beneficiario");
        btnModificaBenficiario.setEnabled(false);

        jTBeneficiarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre", "%", "Parentesco", "Fecha", "Id", "Numero"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                true, true, true, true, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTBeneficiarios.setColumnSelectionAllowed(true);
        jScrollPane1.setViewportView(jTBeneficiarios);
        jTBeneficiarios.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);

        jLabel15.setText("Nombre");

        btnModificarBeneficiario.setText("Modificar Beneficiario");
        btnModificarBeneficiario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarBeneficiarioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPTestamentariaLayout = new javax.swing.GroupLayout(jPTestamentaria);
        jPTestamentaria.setLayout(jPTestamentariaLayout);
        jPTestamentariaLayout.setHorizontalGroup(
            jPTestamentariaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPTestamentariaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPTestamentariaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPTestamentariaLayout.createSequentialGroup()
                        .addComponent(btnAltaBeneficiario)
                        .addGap(18, 18, 18)
                        .addComponent(btnEliminaBeneficiario)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnModificarBeneficiario))
                    .addComponent(jScrollPane1)
                    .addGroup(jPTestamentariaLayout.createSequentialGroup()
                        .addComponent(jLabel15)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNombre1, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtPor1, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel17)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbParen1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel18)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(fecha1, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(155, Short.MAX_VALUE))
            .addGroup(jPTestamentariaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPTestamentariaLayout.createSequentialGroup()
                    .addGap(276, 276, 276)
                    .addComponent(btnModificaBenficiario)
                    .addContainerGap(397, Short.MAX_VALUE)))
        );
        jPTestamentariaLayout.setVerticalGroup(
            jPTestamentariaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPTestamentariaLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPTestamentariaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPTestamentariaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtNombre1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel16)
                        .addComponent(txtPor1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel17)
                        .addComponent(cbParen1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel18)
                        .addComponent(jLabel15))
                    .addComponent(fecha1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPTestamentariaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAltaBeneficiario)
                    .addComponent(btnEliminaBeneficiario)
                    .addComponent(btnModificarBeneficiario))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(80, Short.MAX_VALUE))
            .addGroup(jPTestamentariaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPTestamentariaLayout.createSequentialGroup()
                    .addGap(190, 190, 190)
                    .addComponent(btnModificaBenficiario)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        jTPaneles.addTab("Testamentaria", jPTestamentaria);

        txtNombreBaja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreBajaActionPerformed(evt);
            }
        });

        btnBajaJubilado.setText("Alta Jubilado");

        btnAltaPrograma.setText("Eliminar Jubilado");

        jLabel29.setText("Nombre");

        btnModificarBajaPrograma.setText("Modificar Jubilado");
        btnModificarBajaPrograma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarBajaProgramaActionPerformed(evt);
            }
        });

        jLabel3.setText("Fecha");

        jLabel14.setText("Qna Baja");

        jLabel24.setText("Numero Empleado");

        btnBuscarJubilado.setText("Buscar Jubilado");

        javax.swing.GroupLayout jPTestamentaria1Layout = new javax.swing.GroupLayout(jPTestamentaria1);
        jPTestamentaria1.setLayout(jPTestamentaria1Layout);
        jPTestamentaria1Layout.setHorizontalGroup(
            jPTestamentaria1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPTestamentaria1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPTestamentaria1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPTestamentaria1Layout.createSequentialGroup()
                        .addComponent(btnBajaJubilado)
                        .addGap(18, 18, 18)
                        .addComponent(btnAltaPrograma)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnModificarBajaPrograma)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnBuscarJubilado, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPTestamentaria1Layout.createSequentialGroup()
                        .addComponent(jLabel29)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNombreBaja, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtfechabajaprograma, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtQnaBajaPrograma, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel24)
                        .addGap(18, 18, 18)
                        .addComponent(txtNumeroEmpleadoBaja, javax.swing.GroupLayout.DEFAULT_SIZE, 104, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPTestamentaria1Layout.setVerticalGroup(
            jPTestamentaria1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPTestamentaria1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPTestamentaria1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNombreBaja, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel29)
                    .addComponent(jLabel3)
                    .addComponent(txtfechabajaprograma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14)
                    .addComponent(txtQnaBajaPrograma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel24)
                    .addComponent(txtNumeroEmpleadoBaja, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPTestamentaria1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBajaJubilado)
                    .addComponent(btnAltaPrograma)
                    .addComponent(btnModificarBajaPrograma)
                    .addComponent(btnBuscarJubilado))
                .addContainerGap(253, Short.MAX_VALUE))
        );

        jTPaneles.addTab("Baja Programa", jPTestamentaria1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTPaneles, javax.swing.GroupLayout.PREFERRED_SIZE, 811, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(70, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jTPaneles, javax.swing.GroupLayout.PREFERRED_SIZE, 361, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtPlantelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPlantelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPlantelActionPerformed

    private void btnModificarBeneficiarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarBeneficiarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnModificarBeneficiarioActionPerformed

    private void txtPor1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPor1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPor1ActionPerformed

    private void txtNombre1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombre1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombre1ActionPerformed

    private void cbParenSegundoTerminoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbParenSegundoTerminoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbParenSegundoTerminoActionPerformed

    private void txtNombreSegundoTerminoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreSegundoTerminoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreSegundoTerminoActionPerformed

    private void txtFechaAfiliacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFechaAfiliacionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFechaAfiliacionActionPerformed

    private void txtEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmpleadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmpleadoActionPerformed

    private void txtNombreBajaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreBajaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreBajaActionPerformed

    private void btnModificarBajaProgramaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarBajaProgramaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnModificarBajaProgramaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton BtnModificarSegundoTermino;
    public javax.swing.JButton btnAlta;
    public javax.swing.JButton btnAltaBeneficiario;
    public javax.swing.JButton btnAltaBeneficiarioSegundoTermino;
    public javax.swing.JButton btnAltaPrograma;
    public javax.swing.JButton btnBajaJubilado;
    public javax.swing.JButton btnBuscar;
    public javax.swing.JButton btnBuscarJubilado;
    public javax.swing.JButton btnBuscarNomina;
    public javax.swing.JButton btnEliminaBeneficiario;
    public javax.swing.JButton btnEliminaBeneficiarioSegundoTermino;
    public javax.swing.JButton btnEliminar;
    public javax.swing.JButton btnLimpiar;
    public javax.swing.JButton btnModificaBenficiario;
    public javax.swing.JButton btnModificar;
    public javax.swing.JButton btnModificarBajaPrograma;
    public javax.swing.JButton btnModificarBeneficiario;
    public javax.swing.JComboBox<String> cbEstadoCivil;
    public javax.swing.JComboBox<String> cbParen1;
    public javax.swing.JComboBox<String> cbParenSegundoTermino;
    public javax.swing.JComboBox<String> cbSexo;
    public javax.swing.JComboBox<String> cbSindicato;
    public com.toedter.calendar.JDateChooser fecha1;
    public com.toedter.calendar.JDateChooser fechaIngreso;
    public com.toedter.calendar.JDateChooser fechaSegundoTermino;
    public javax.swing.JLabel jLabel1;
    public javax.swing.JLabel jLabel10;
    public javax.swing.JLabel jLabel11;
    public javax.swing.JLabel jLabel12;
    public javax.swing.JLabel jLabel13;
    public javax.swing.JLabel jLabel14;
    public javax.swing.JLabel jLabel15;
    public javax.swing.JLabel jLabel16;
    public javax.swing.JLabel jLabel17;
    public javax.swing.JLabel jLabel18;
    public javax.swing.JLabel jLabel19;
    public javax.swing.JLabel jLabel2;
    public javax.swing.JLabel jLabel20;
    public javax.swing.JLabel jLabel21;
    public javax.swing.JLabel jLabel22;
    public javax.swing.JLabel jLabel23;
    public javax.swing.JLabel jLabel24;
    public javax.swing.JLabel jLabel25;
    public javax.swing.JLabel jLabel26;
    public javax.swing.JLabel jLabel29;
    public javax.swing.JLabel jLabel3;
    public javax.swing.JLabel jLabel4;
    public javax.swing.JLabel jLabel5;
    public javax.swing.JLabel jLabel6;
    public javax.swing.JLabel jLabel7;
    public javax.swing.JLabel jLabel8;
    public javax.swing.JLabel jLabel9;
    public javax.swing.JPanel jPSegundoTermino;
    public javax.swing.JPanel jPTestamentaria;
    public javax.swing.JPanel jPTestamentaria1;
    public javax.swing.JPanel jPanel1;
    public javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JScrollPane jScrollPane2;
    public javax.swing.JTable jTBeneficiarios;
    public javax.swing.JTable jTBeneficiariosSegundoTermino;
    public javax.swing.JTabbedPane jTPaneles;
    public javax.swing.JTextField txtCategoria;
    public javax.swing.JTextField txtCelular;
    public javax.swing.JTextField txtCorreo;
    public javax.swing.JTextField txtDireccion;
    public javax.swing.JTextField txtEmpleado;
    public javax.swing.JTextField txtFechaAfiliacion;
    public javax.swing.JTextField txtNombre;
    public javax.swing.JTextField txtNombre1;
    public javax.swing.JTextField txtNombreBaja;
    public javax.swing.JTextField txtNombreSegundoTermino;
    public javax.swing.JTextField txtNumeroEmpleadoBaja;
    public javax.swing.JTextField txtPlantel;
    public javax.swing.JTextField txtPor1;
    public javax.swing.JTextField txtQnaAfiliacion;
    public javax.swing.JTextField txtQnaBajaPrograma;
    public javax.swing.JTextField txtRfc;
    public javax.swing.JTextField txtSueldo;
    public javax.swing.JTextField txtTelefono;
    public javax.swing.JTextField txtfechabajaprograma;
    // End of variables declaration//GEN-END:variables
}
