/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

/**
 *
 * @author victor
 */
public class frmReporteTrimestral extends javax.swing.JInternalFrame {

    /**
     * Creates new form frmReporteTrimestral
     */
    public frmReporteTrimestral() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnReporteTrimestral = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        cbperiodoinicial = new javax.swing.JComboBox<>();
        cbnumeroinicial = new javax.swing.JComboBox<>();
        btnCalcularRendimientos = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setTitle("Reporte Trimestral");

        btnReporteTrimestral.setText("Generar Reporte Trimestral");

        jLabel5.setText("Reporte");

        cbperiodoinicial.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2009", "2010", "2011", "2012", "2013", "2014", "2015", "2016", "2017", "2018", "2019", "2020", "2021", "2022", "2023", "2024", "2025" }));
        cbperiodoinicial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbperiodoinicialActionPerformed(evt);
            }
        });

        cbnumeroinicial.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "01", "02", "03", "04" }));
        cbnumeroinicial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbnumeroinicialActionPerformed(evt);
            }
        });

        btnCalcularRendimientos.setText("Calcular Rendimientos");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnCalcularRendimientos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnReporteTrimestral, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(cbperiodoinicial, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbnumeroinicial, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(128, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(cbperiodoinicial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbnumeroinicial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addComponent(btnReporteTrimestral)
                .addGap(18, 18, 18)
                .addComponent(btnCalcularRendimientos)
                .addContainerGap(147, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbperiodoinicialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbperiodoinicialActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbperiodoinicialActionPerformed

    private void cbnumeroinicialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbnumeroinicialActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbnumeroinicialActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnCalcularRendimientos;
    public javax.swing.JButton btnReporteTrimestral;
    public javax.swing.JComboBox<String> cbnumeroinicial;
    public javax.swing.JComboBox<String> cbperiodoinicial;
    private javax.swing.JLabel jLabel5;
    // End of variables declaration//GEN-END:variables
}
